# Generated by Django 5.2.8 on 2025-11-09 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="Type of event tracked (e.g., 'surah_viewed', 'reciter_played')", max_length=100, verbose_name='Event Type')),
                ('event_data', models.JSONField(help_text='Flexible metadata storage (no PII allowed)', verbose_name='Event Data')),
                ('user_id_hash', models.CharField(blank=True, help_text='SHA-256 hashed user ID for anonymization', max_length=64, null=True, verbose_name='User ID Hash')),
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Anonymous session tracking', verbose_name='Session ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Event occurrence time', verbose_name='Timestamp')),
                ('country_code', models.CharField(blank=True, help_text='Country-level location (2-letter ISO code) - no city/coordinates', max_length=2, null=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytics_a_event_t_64745b_idx'), models.Index(fields=['timestamp'], name='analytics_a_timesta_aef2a5_idx')],
            },
        ),
    ]
