# Generated by Django 5.2.8 on 2025-11-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Privacy policy content in Markdown format', verbose_name='Content')),
                ('version', models.CharField(help_text="Version identifier (e.g., '1.0', '2.0')", max_length=20, unique=True, verbose_name='Version')),
                ('effective_date', models.DateField(help_text='Date when this policy version becomes effective', verbose_name='Effective Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current active policy', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-effective_date'],
            },
        ),
    ]
