# Generated by Django 5.2.8 on 2025-11-18 20:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_arabic', models.TextField(help_text='Arabic name of the Surah')),
                ('name_english', models.CharField(help_text='English name of the Surah', max_length=100)),
                ('name_transliteration', models.CharField(help_text='Transliterated name of the Surah', max_length=100)),
                ('revelation_type', models.CharField(choices=[('Meccan', 'Meccan'), ('Medinan', 'Medinan')], help_text='Place of revelation (Meccan or Medinan)', max_length=10)),
                ('revelation_order', models.IntegerField(help_text='Chronological order of revelation (1-114)')),
                ('revelation_note', models.TextField(blank=True, default='', help_text='Notes about mixed revelation status')),
                ('total_verses', models.IntegerField(help_text='Total number of verses in this Surah')),
                ('mushaf_page_start', models.IntegerField(help_text='Starting page in the Mushaf (1-604)')),
                ('juz_start', models.IntegerField(help_text='Starting Juz number (1-30)')),
            ],
            options={
                'verbose_name': 'Surah',
                'verbose_name_plural': 'Surahs',
                'db_table': 'quran_surah',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['revelation_order'], name='idx_surah_revelation_order')],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.IntegerField(help_text='Verse number within the Surah')),
                ('text_uthmani', models.TextField(help_text='Uthmani script with full diacritics and Tajweed marks')),
                ('text_simple', models.TextField(help_text='Simplified Arabic text without diacritics')),
                ('juz_number', models.IntegerField(help_text='Juz (part) number (1-30)')),
                ('mushaf_page', models.IntegerField(help_text='Page number in the Mushaf (1-604)')),
                ('hizb_quarter', models.IntegerField(help_text='Hizb quarter number (1-240)')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL full-text search vector', null=True)),
                ('surah', models.ForeignKey(help_text='The Surah this verse belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Verse',
                'verbose_name_plural': 'Verses',
                'db_table': 'quran_verse',
                'ordering': ['surah', 'verse_number'],
                'indexes': [models.Index(fields=['surah', 'verse_number'], name='idx_verse_surah_number'), models.Index(fields=['juz_number'], name='idx_verse_juz_number'), models.Index(fields=['mushaf_page'], name='idx_verse_mushaf_page'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_verse_search_vector')],
                'unique_together': {('surah', 'verse_number')},
            },
        ),
    ]
